version: "3.9"

services:
  backend:
    build: ./backend
    container_name: hacknu25
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hacknu25
      POSTGRES_PASSWORD: hacknu25
      POSTGRES_DB: hacknu25
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
